### ISSUE TITLE
v2.9.0 logger still does not work with off-cluster redis

### ISSUE THREAD

**Issue by rimusz** [deis/logger#127]
`$ kubectl -n deis logs deis-logger-3305119006-ixc1p
2016/12/06 11:44:46 config error: envconfig.Process: assigning LOGGER_DEIS_LOGGER_REDIS_SERVICE_PORT to DEIS_LOGGER_REDIS_SERVICE_PORT: converting 'redis port' to type int:`

**Comment by dhilipsiva** [comment]
### More Context:

I am running on Kubernetes 1.4.6 on GKE with deis version 2.9.0 with helm
```
Client: &version.Version{SemVer:"v2.0.1", GitCommit:"dc87ea8dd0111164c720fd13b4eb8a905f97ac62", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.1", GitCommit:"dc87ea8dd0111164c720fd13b4eb8a905f97ac62", GitTreeState:"clean"}
```

I am trying to deply an `off-cluster` redis with configuration:
```
logger:
  redis:
    # Configure the following ONLY if using an off-cluster Redis instance for logger
    db: "logdb"
    host: "1.2.3.4"
    port: 6379
    password: "" # "" == no password
```

But my deis logger fails with error:
```
2016-12-06T11:04:28.958212521Z 2016/12/06 11:04:28 config error: envconfig.Process: assigning LOGGER_DEIS_LOGGER_REDIS_SERVICE_PORT to DEIS_LOGGER_REDIS_SERVICE_PORT: converting 'redis port' to type int: 
```
